version: '3.6'

services:

  codelifter.covid19.admin:
    container_name: codelifter-covid19-admin
    image: ${DOCKER_REGISTRY-}codeliftercovid19admin
    build:
      context: .
      dockerfile: CodeLifter.Covid19.Admin/Dockerfile
    networks:
      - covidapinet
    environment:
      SQLSERVER_SA_PASSWORD: ${SQLSERVER_SA_PASSWORD}
      GITHUB_AUTH_TOKEN: ${GITHUB_AUTH_TOKEN}

  covidapi.codelifter.io:
    container_name: covidapi-codelifter-io
    image: ${DOCKER_REGISTRY-}covidapicodelifterio
    build:
      context: .
      dockerfile: CovidApi.CodeLifter.IO/Dockerfile
    networks:
      - covidapinet
    environment:
      SQLSERVER_SA_PASSWORD: ${SQLSERVER_SA_PASSWORD}
      GITHUB_AUTH_TOKEN: ${GITHUB_AUTH_TOKEN}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

networks:
  covidapinet: 
    name: covidapinet
