version: '3.6'

services:
  covidapi.codelifter.io:
    container_name: "VS-covidapi-codelifter-io"
    image: codelifterio/covidapi-codelifter-io
    build:
      context: .
      dockerfile: CovidApi.CodeLifter.IO/Dockerfile
    networks:
      - covidapinet
    ports:
      - "8180:80"
      - "8143:443"
    depends_on:
      - covidapi-codelifter-data
    env_file: 
      - ./Docker/ENV/vs.env
    links:
      - covidapi-codelifter-data

  covidapi-codelifter-data:
    container_name: "VS-covidapi-codelifter-data"
    image: codelifterio/covidapi-codelifter-data
    networks:
      - covidapinet
    ports:
      - "1431:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    env_file: 
      - ./Docker/ENV/vs.env
    environment:
      ACCEPT_EULA: "Y"

  covidapi-codelifter-azurite:
    container_name: "VS-covidapi-codelifter-azurite"
    image: mcr.microsoft.com/azure-storage/azurite:latest
    networks:
      - covidapinet
    ports:
      - "12000:10000"
      - "12001:10001"

volumes:
  mssql-data:

networks:
  covidapinet: 
    name: covidapinet
