version: '3.6'

services:
  covidapi.codelifter.io:
    container_name: covidapi-codelifter-io
    image: ${DOCKER_REGISTRY-}covidapicodelifterio
    build:
      context: .
      dockerfile: CovidApi.CodeLifter.IO/Dockerfile
    networks:
      - covidapinet
    depends_on:
      - covidapi-codelifter-data
    environment:
      SQLSERVER_SA_PASSWORD: ${SQLSERVER_SA_PASSWORD}
      GITHUB_AUTH_TOKEN: ${GITHUB_AUTH_TOKEN}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    links:
      - covidapi-codelifter-data

  covidapi-codelifter-data:
    container_name: covidapi-codelifter-data
    image: codelifterio/covidapi-codelifter-data:05-19-2020
    networks:
      - covidapinet
    ports:
      - "1401:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      SA_PASSWORD: ${SQLSERVER_SA_PASSWORD}
      ACCEPT_EULA: "Y"

volumes:
  mssql-data:

networks:
  covidapinet: 
    name: covidapinet
