version: '3.6'

services:

  covidapi.codelifter.io:
    container_name: "covidapi-codelifter-io"
    image: codelifterio/covidapi-codelifter-io
    build:
      context: .
      dockerfile: CovidApi.CodeLifter.IO/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    env_file: 
    - ./Docker/ENV/release.env

  covidapi-codelifter-functions:
    container_name: "covidapi-codelifter-functions"
    image: mcr.microsoft.com/azure-functions/dotnet:3.0
    build:
      context: .
      dockerfile: CodeLifter.IO.CovidApi.Functions/Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    env_file: 
    - ./Docker/ENV/release.env
