version: '3.4'

services:
  covidapi.codelifter.io:
    image: ${DOCKER_REGISTRY-}covidapicodelifter
    build:
      context: .
      dockerfile: CovidApi.CodeLifter.IO/Dockerfile
    depends_on:
      - db
    environment:
      SQL_CONNECTION_STRING: ${SQL_CONNECTION_STRING}
      GITHUB_AUTH_TOKEN: ${GITHUB_AUTH_TOKEN}
      ADMIN_AUTH_TOKEN: ${ADMIN_AUTH_TOKEN}
    links:
      - db

  db:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      SA_PASSWORD: ${SQLSERVER_SA_PASSWORD}
      ACCEPT_EULA: "Y"

volumes:
  mssql-data:
