version: '3.6'

services:

  covidapi.codelifter.admin:
    container_name: covidapi-codelifter-admin
    image: codelifterio/covidapi-codelifter-admin
    build:
      context: .
      dockerfile: CodeLifter.Covid19.Admin/Dockerfile
    networks:
      - covidapinet
    depends_on:
      - covidapi-codelifter-data
    environment:
      SQLSERVER_DATASOURCE: ${SQLSERVER_DATASOURCE}
      SQLSERVER_CATALOG: ${SQLSERVER_CATALOG}
      SQLSERVER_USER_ID: ${SQLSERVER_USER_ID}
      SQLSERVER_USER_PASSWORD: ${SQLSERVER_USER_PASSWORD}
    links:
      - covidapi-codelifter-data

  covidapi.codelifter.io:
    container_name: covidapi-codelifter-io
    image: codelifterio/covidapi-codelifter-io
    build:
      context: .
      dockerfile: CovidApi.CodeLifter.IO/Dockerfile
    networks:
      - covidapinet
    ports:
      - "6680:80"
      - "6666:443"
    depends_on:
      - covidapi-codelifter-data
      - covidapi-codelifter-redis
    environment:
      SQLSERVER_DATASOURCE: ${SQLSERVER_DATASOURCE}
      SQLSERVER_CATALOG: ${SQLSERVER_CATALOG}
      SQLSERVER_USER_ID: ${SQLSERVER_USER_ID}
      SQLSERVER_USER_PASSWORD: ${SQLSERVER_USER_PASSWORD}
    links:
      - covidapi-codelifter-data

  covidapi-codelifter-data:
    container_name: covidapi-codelifter-data
    image: codelifterio/covidapi-codelifter-data:06-01-2020
    networks:
      - covidapinet
    ports:
      - "1401:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      SQLSERVER_DATASOURCE: ${SQLSERVER_DATASOURCE}
      SQLSERVER_CATALOG: ${SQLSERVER_CATALOG}
      SQLSERVER_USER_ID: ${SQLSERVER_USER_ID}
      SQLSERVER_USER_PASSWORD: ${SQLSERVER_USER_PASSWORD}
      ACCEPT_EULA: "Y"

  covidapi-codelifter-redis:
    container_name: covidapi-codelifter-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - covidapinet

volumes:
  mssql-data:

networks:
  covidapinet: 
    name: covidapinet
