version: '3.6'

services:

  covidapi.codelifter.io:
    container_name: covidapi-codelifter-io
    image: codelifterio/covidapi-codelifter-io
    build:
      context: .
      dockerfile: CovidApi/Dockerfile
    networks:
      - covidapinet
    ports:
      - "8180:80"
      - "8143:443"
    depends_on:
      - covidapi-codelifter-data
      - covidapi-codelifter-redis
    env_file:
      - docker.Debug.env
    links:
      - covidapi-codelifter-data
      - covidapi-codelifter-redis

  covidapi-codelifter-data:
    container_name: covidapi-codelifter-data
    image: "postgres" 
    ports: 
      - "5434:5432"
    env_file:
      - docker.Debug.env
    restart: unless-stopped
    volumes:
      - covid-data:/var/lib/postgresql/data/
    networks:
      - covidapinet

  covidapi-codelifter-redis:
    container_name: covidapi-codelifter-redis
    image: redis:alpine
    ports:
      - "6381:6379"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - covidapinet

volumes:
  covid-data:

networks:
  covidapinet: 
