version: '3.6'

services:

  codelifter.covid19.admin:
    container_name: codelifter-covid19-admin
    image: ${DOCKER_REGISTRY-}codeliftercovid19admin
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - covidapinet
    environment:
      SQLSERVER_SA_PASSWORD: ${SQLSERVER_SA_PASSWORD}
      GITHUB_AUTH_TOKEN: ${GITHUB_AUTH_TOKEN}

networks:
  covidapinet: 
    name: covidapinet