version: '3.6'

services:
  covidapi.codelifter.io:
    container_name: covidapi-codelifter-io
    image: ${DOCKER_REGISTRY-}covidapicodelifterio
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - covidapinet
    depends_on:
      - covidapi-codelifter-data
    environment:
      SQLSERVER_SA_PASSWORD: ${SQLSERVER_SA_PASSWORD}
      GITHUB_AUTH_TOKEN: ${GITHUB_AUTH_TOKEN}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    links:
      - covidapi-codelifter-data


networks:
  covidapinet: 
    name: covidapinet